export { default as ComingSoonPage } from './ComingSoonPage'
export { default as CategoriesPage } from './CategoriesPage'
export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as ProfilePage } from './ProfilePage'
export { default as RegisterPage } from './RegisterPage'
